### ISSUE TITLE
Unable to load OAUTH.v2 Module

### ISSUE THREAD

**Issue by TamirTwina** [pwielgolaski/teamcity-oauth#1]
Hi, 
I've installed the plugin on Teamcity v9.1 
after adding the configuration to the auth-config.xml 
I get a warning in teamcity UI saying  

> Failed to enable authentication module: HTTP-OAUTH.v2

Any idea what's wrong with the configuration ?

**Comment by jordanlewis** [comment]
Also experiencing this problem.

**Comment by jordanlewis** [comment]
Actually, I had misspelled the plugin name. It's working ok for me.

**Comment by TamirTwina** [comment]
I've added the following to my auth-config.xml (filling the client ID & Secret) :
Should i have done something differently ? 
```

<auth-module type="HTTP-OAUTH.v2">
      <property key="allowCreatingNewUsersByLogin">true</property>
      <property key="tokenEndpoint">https://github.com/login/oauth/access_token</property>
      <property key="userEndpoint">https://api.github.com/user</property>
      <property key="clientId">{{ CLIENT_ID }}</property>
      <property key="scope">user</property>
      <property key="authorizeEndpoint">https://github.com/login/oauth/authorize</property>
      <property key="clientSecret">{{ CLIENT_SECRET }}</property>
      <property key="allowMatchingUsersByEmail">false</property>
    </auth-module>
```

**Comment by jordanlewis** [comment]
That's pretty much the same as what I have. Maybe you have not added the plugin .zip to the server's plugins directory?

**Comment by TamirTwina** [comment]
Got it :) used the zip for github release and not Bintray (Doh!) 
It works ok, only missing the github callback url to teamcity 
@jordanlewis  what did you use in your setup ?

**Comment by jordanlewis** [comment]
Use your TeamCity base url.

**Comment by TamirTwina** [comment]
Cool , thanks 👍
