### ISSUE TITLE
"Allow creating new users on the first login" always true

### ISSUE THREAD

**Issue by jurgisp** [pwielgolaski/teamcity-oauth#13]
Great plugin, exactly what I needed, and luckily Google OAuth was added just a few days ago!

I managed to set it up successfully on my TeamCity server, only one problem though - it seems to be creating new users even if I uncheck the box "Allow creating new users on the first login". I want to restrict only to existing users, because otherwise anyone with any Google account can log in.

From what I can see here https://github.com/pwielgolaski/teamcity-oauth/blob/master/src/main/java/jetbrains/buildServer/auth/oauth/ServerPrincipalFactory.java, the `getServerPrincipal()` method always creates new user if not found. Do I understand correctly, that the check should be there, or how is the setting taken into account?

**Comment by pwielgolaski** [comment]
silly me, I removed when I was adding new feature 
https://github.com/pwielgolaski/teamcity-oauth/commit/87b9fb8168b1269953d44d14d9497edb6c760204#diff-54890d1dd1c8ceaed3febff5f718602fL38

I reintroduced it https://github.com/pwielgolaski/teamcity-oauth/commit/5a831c07318305e35dcf78453a029fccf5292145

**Comment by jurgisp** [comment]
Thanks, it works now!
