### ISSUE TITLE
Add permission support

### ISSUE THREAD

**Issue by callum-p** [pwielgolaski/teamcity-oauth#18]
This plugin is pretty useless (sorry for the harsh words) as-is because it allows anyone to sign up on your TC server.  Sure you can make it so it doesn't create new users but what would be the point then - you might as well just create users manually. 

There should be some sort of permission model like being able to restrict it to users from a specific github organization, and further permission levels based around that organizations groups.

**Comment by pwielgolaski** [comment]
support for organization was added now
