### ISSUE TITLE
Gitlab integration

### ISSUE THREAD

**Issue by kemsky** [pwielgolaski/teamcity-oauth#24]
Hi,

Is it possible to make it work with GitLab?

I've tried Custom preset, but could not find user endpoint in GitLabdocumentation. Created GitLab application and used App Id/Secret as Client id/Secret.

Current error message is: `Unauthenticated since failed to fetch token for code ...`.

https://docs.gitlab.com/ee/api/oauth2.html

**Comment by kemsky** [comment]
I have already dirty fixed that in `getAccessToken` method according to GitLab documentation:

```java
    public String getAccessToken(String code) throws IOException {
        HttpUrl.Builder builder = HttpUrl.parse(properties.getTokenEndpoint())
                .newBuilder()
                .addQueryParameter("client_id", properties.getClientId())
                .addQueryParameter("client_secret", properties.getClientSecret())
                .addQueryParameter("code", code)
                .addQueryParameter("grant_type", "authorization_code")
                .addQueryParameter("redirect_uri", properties.getRootUrl());

        Request request = new Request.Builder()
                .url(builder.build().toString())
                .addHeader("Accept", MediaType.APPLICATION_JSON_VALUE)
                .post(new FormBody.Builder().build())
                .build();
        Response response = getHttpClient().newCall(request).execute();
        Map jsonResponse = (Map) JSONValue.parse(response.body().string());
        return (String) jsonResponse.get("access_token");
    }
```
For some reason it requires query parameters instead of form data (we have standalone version).

Authorization URL: `https://domain.com/oauth/authorize`
Token URL: `https://domain.com/oauth/token`
User URL: `https://domain.com/api/v4/user`

Scope: `api`

**Comment by madnut-ua** [comment]
@pwielgolaski Any chance to have GitLab integration in place?

**Comment by pwielgolaski** [comment]
I was able to authenticate using Custom preset, so maybe you should try
![image](https://user-images.githubusercontent.com/3696319/62824620-089ac400-bba1-11e9-850f-0653587deb91.png)

If there is need for some customization I'm open for PR.
