### ISSUE TITLE
Get userinfo by Authorization header

### ISSUE THREAD

**Issue by alhardy** [pwielgolaski/teamcity-oauth#3]
Any chance an option could be exposed in configuration to pass the access token in the Authorization header rather than as a query string param?

**Comment by pwielgolaski** [comment]
Agresji, dont think it need to be option, it could be default

**Comment by alhardy** [comment]
Yes default would be good 👍

**Comment by pwielgolaski** [comment]
Added in latest release https://github.com/pwielgolaski/teamcity-oauth/releases/tag/teamcity-oauth-1.0.3
