### ISSUE TITLE
Is there plans to perform real validation of the certificate and ensure the payload hasn't been tampered with?

### ISSUE THREAD

**Issue by NickJosevski** [pwielgolaski/teamcity-oauth#8]
There's only `AcceptEverythingTrustManager` so far, with no other notes, or issues raised (just seeing if you guys are still working on this)?

**Comment by pwielgolaski** [comment]
Open to make it as configuration switch, user can decide if it is on/off.

**Comment by pwielgolaski** [comment]
Fixed by https://github.com/pwielgolaski/teamcity-oauth/commit/8c2f3792492b3f0a4718183a9488e5a7ac6e3dbb
